name: Build CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  Build-kpimg:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Generate version
        id: parse_version
        run: |
          MAJOR=$(grep '#define MAJOR' version | awk '{print $3}' | tr -d '\r')
          MINOR=$(grep '#define MINOR' version | awk '{print $3}' | tr -d '\r')
          PATCH=$(grep '#define PATCH' version | awk '{print $3}' | tr -d '\r')
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Generated Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Compiler
        run: |
          curl -o arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
          tar -Jxf arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz

      - name: Build kpimg
        run: |
          export TARGET_COMPILE=`pwd`/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-
          cd kernel
          export ANDROID=1
          make

          cp kpimg ../manager/app/src/main/assets/kpimg

      - name: Upload kpimg artifact
        uses: actions/upload-artifact@v4
        with:
          name: kpimg
          path: manager/app/src/main/assets/kpimg

  Build-android-kptools:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b
          add-to-path: true

      - name: Make hdr
        run: |
          export TARGET_COMPILE=placeholder
          cd kernel
          make hdr

      - name: Build kptools-android
        run: |
          cd tools
          mkdir -p build/android && cd build/android
          echo ${{ steps.setup-ndk.outputs.ndk-path }}
          cmake \
            -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DANDROID_PLATFORM=android-33 \
            -DANDROID_ABI=arm64-v8a ../..
          cmake --build .

          mkdir -p ../../../manager/app/libs/arm64-v8a
          cp kptools ../../../manager/app/libs/arm64-v8a/libkptools.so

      - name: Upload libkptools artifact
        uses: actions/upload-artifact@v4
        with:
          name: libkptools
          path: manager/app/libs/arm64-v8a/libkptools.so

      - name: Upload kptools binary
        uses: actions/upload-artifact@v4
        with:
          name: kptools-binary
          path: tools/build/android/kptools

  build-manager:
    runs-on: ubuntu-latest
    needs: [Build-kpimg, Build-android-kptools]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate version
        id: parse_version
        run: |
          MAJOR=$(grep '#define MAJOR' version | awk '{print $3}' | tr -d '\r')
          MINOR=$(grep '#define MINOR' version | awk '{print $3}' | tr -d '\r')
          PATCH=$(grep '#define PATCH' version | awk '{print $3}' | tr -d '\r')
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Generated Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Download kpimg
        uses: actions/download-artifact@v4
        with:
          name: kpimg
          path: manager/app/src/main/assets

      - name: Download libkptools
        uses: actions/download-artifact@v4
        with:
          name: libkptools
          path: manager/app/libs/arm64-v8a

      - name: Download kptools binary
        uses: actions/download-artifact@v4
        with:
          name: kptools-binary
          path: tools/build/android

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: jetbrains
          java-version: 21
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: ''

      - name: Build with Gradle
        working-directory: manager
        run: |
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          sed -i 's/org.gradle.configuration-cache=true//g' gradle.properties
          chmod +x gradlew
          ./gradlew clean assembleDebug assembleRelease

      - name: Upload build APKs
        uses: actions/upload-artifact@v4
        with:
          name: KPM-Manager
          path: |
            manager/app/build/outputs/apk/debug/*.apk
            manager/app/build/outputs/apk/release/*.apk

      - name: Release APK and Binaries
        if: ${{ github.ref_type == 'tag' }}
        continue-on-error: true
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ github.token }}
          tag: ${{ steps.parse_version.outputs.VERSION }}
          artifacts: |
            manager/app/build/outputs/apk/release/*.apk
            kernel/kpimg
            tools/build/android/kptools
          generateReleaseNotes: true
          makeLatest: true
          replacesArtifacts: true
