name: Build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release Tag Name (e.g. v2.0.0)'
        required: true
        type: string
      release_title:
        description: 'Optional Custom Release Title'
        required: false
        default: ''
        type: string

permissions:
  contents: write

jobs:
  build-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5.5.0
        with:
          distribution: temurin
          java-version: 21
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: ''

      - name: Build with Gradle
        run: |
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          sed -i 's/org.gradle.configuration-cache=true//g' gradle.properties
          chmod +x gradlew
          ./gradlew clean assembleDebug assembleRelease

      - name: Upload build APKs
        uses: actions/upload-artifact@v7
        with:
          name: KPM-Manager
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*.apk

      - name: Release APK and Binaries
        uses: ncipollo/release-action@v1.21.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ inputs.release_title != '' && inputs.release_title || format('KPM-Manager {0}', inputs.tag_name) }}
          tag: ${{ inputs.tag_name }}
          allowUpdates: true
          artifacts: |
            app/build/outputs/apk/release/*.apk
          generateReleaseNotes: true
          makeLatest: true
          replacesArtifacts: true
